auth:
    method: pgi-ad
aws:
    default-profile: false
    ttl: 8h
    use-profiles: true
    web-ttl: 8h
vault-address: https://vault.pgi-tools.com
vault-initial-token-duration: 8h
vault-username: esherman
kube:
    cluster:
        filter: icekube.net
